version: '3.8'
services:
  appseed-app:
    container_name: appseed_app
    restart: always
    env_file: .env
    build: .
    networks:
      - db_network
      - web_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
 